[package]
org = "ballerinax"
name = "java.jdbc"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "@toml.version@"
path = "../native/build/libs/java.jdbc-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@sql.version@"
path = "./lib/sql-native-@sql.native.version@.jar"
