[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/java.jdbc-native-1.3.0.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.3.0.jar"

[[platform.java11.dependency]]
path = "./lib/h2-2.0.206.jar"
scope = "testOnly"
