[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.12.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "1.12.0"
path = "../native/build/libs/java.jdbc-native-1.12.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.14.0"
path = "./lib/sql-native-1.14.0-20240814-162300-116ead6.jar"
