[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.14.1"
authors = ["Ballerina"]
keywords = ["client", "network", "SQL", "RDBMS", "JDBC", "Vendor/Java", "Area/Database", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "1.14.1"
path = "../native/build/libs/java.jdbc-native-1.14.1.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.16.0"
path = "./lib/sql-native-1.16.0.jar"
