[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.1.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/java.jdbc-native-1.1.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.1.1-20211126-000600-ddbfeed.jar"
