[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.6.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "1.6.0"
path = "../native/build/libs/java.jdbc-native-1.6.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.6.0"
path = "./lib/sql-native-1.6.0-20221014-221200-0061889.jar"

[[platform.java11.dependency]]
path = "./lib/h2-2.1.212.jar"
scope = "testOnly"
