[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.8.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jdbc-native"
version = "1.8.0"
path = "../native/build/libs/java.jdbc-native-1.8.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.8.0"
path = "./lib/sql-native-1.8.0-20230403-171600-223bb14.jar"

[[platform.java11.dependency]]
path = "./lib/h2-2.1.212.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "../native-image-configs/build/libs/java.jdbc-native-image-configs-1.8.0-SNAPSHOT.jar"
scope = "testOnly"
