[package]
org = "ballerinax"
name = "java.jdbc"
version = "1.2.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "JDBC"]
repository = "https://github.com/ballerina-platform/module-ballerinax-java.jdbc"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/java.jdbc-native-1.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.2.0-20211212-134300-e7bd4fe.jar"
