[plugin]
id = "jdbc-compiler-plugin"
class = "io.ballerina.stdlib.java.jdbc.compiler.JDBCCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/java.jdbc-compiler-plugin-1.14.1-SNAPSHOT.jar"
