[package]
org = "wso2"
name = "cache_with_cleanup_task"
version = "0.0.1"

[build-options]
cloud = "k8s"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"
